name: "Jest Code Coverage Report"
description: "Comments a pull request with the jest code coverage"
author: "Zeeshan Ahmad"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "Github token"
    required: true
  test-command:
    description: "Specify a command to run the tests"
    required: false
  coverage-info-location:
    description: "Specify the location of the coverage info, defaults to './coverage/lcov.info'"
    required: false
runs:
  using: "node20"
  main: "index.js"
